---
name: "Setup Go Workspace"
description: "Configure Go and prepare the workspace"

runs:
  using: composite
  steps:
    - name: Set up Golang
      uses: actions/setup-go@v5
      with:
        go-version: "1.24"

    - name: Install Just
      uses: extractions/setup-just@v2

    - name: Install Go modules
      shell: bash
      run: |
        just tidy

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install requirements
      shell: bash
      run: uv sync --locked --all-extras --dev
