name: Release

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
      - "docs/**"
      - ".gitignore"
      - "LICENSE"
      - ".github/**"

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip release]') }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Release
        uses: ./shared-actions/create-release
        with:
          spec-file: specs.json
          git-token: ${{ secrets.GITHUB_TOKEN }}
          release-notes-dir: .github/release
